In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
class linear_regression:
    def __init__(self, alpha=0.1, n_rounds=1000, eps=1e-6):
        self.alpha = alpha 
        self.n_rounds = n_rounds
        self.eps = eps  # 预测误差的阈值
    
    def fit(self, X, y):
        np.atleast_2d(X)
        X = np.c_[X, np.ones(X.shape[0])] # 增加一个特征，表示常数项
        n_features = X.shape[1] 
        self.betas = np.zeros((n_features,1))
        for i in range(self.n_rounds):
            epsilon = y - np.dot(X, self.betas)
            if np.sum(np.square(epsilon)) <= self.eps:
                # 若误差平方和小于1r-6，则退出梯度下降过程
                break
            gradient = -np.dot(X.T, epsilon)
            self.betas -= self.alpha * gradient
        print(self.betas)
    
    def predict(self, X):
        np.atleast_2d(X)
        X = np.c_[X, np.ones(X.shape[0])]
        return np.dot(X, self.betas)
    
    def get_betas(self):
        return self.betas

拟合方程: 
$$y=3x_1+2x_2+1$$

In [3]:
X = np.array([[0,0],[1,1],[1,2,],[2,2]])
y = np.array([[1],[6],[8],[11]])
lr = linear_regression(alpha=0.1, n_rounds=1000)
lr.fit(X, y)

[[2.99870003]
 [2.00109098]
 [0.99993034]]


In [4]:
lr.get_betas()

array([[2.99870003],
       [2.00109098],
       [0.99993034]])

### sklearn中的线性回归

In [5]:
sk_lr = LinearRegression()
sk_lr.fit(X, y)
print(sk_lr.coef_, sk_lr.intercept_)

[[3. 2.]] [1.]


In [6]:
np.square(2)

4