In [43]:
import torch
import torch.nn as nn

In [2]:
torch.__version__

'1.2.0+cu92'

In [3]:
torch.cuda.is_available()

True

In [10]:
x = torch.empty(5, 3)
x

tensor([[9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38],
        [1.1112e-38, 1.0561e-38, 9.9184e-39],
        [1.0653e-38, 4.1327e-39, 1.0194e-38],
        [1.0469e-38, 8.9082e-39, 1.5134e-43]])

In [11]:
x = torch.rand(5, 3)
x

tensor([[0.6792, 0.8937, 0.4167],
        [0.4030, 0.2417, 0.2457],
        [0.1718, 0.3932, 0.2002],
        [0.5415, 0.0655, 0.3466],
        [0.2842, 0.6628, 0.1090]])

In [13]:
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [16]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


tensor([[-1.7858, -0.8826, -0.7852],
        [ 1.0577,  0.7125, -0.3111],
        [-1.4346, -0.3935,  0.8644],
        [ 0.3628, -0.2221,  0.6360],
        [ 0.3794, -1.6382, -0.1091]])

In [22]:
x.size()

torch.Size([5, 3])

In [24]:
result = torch.empty(5, 3)
y = torch.rand(5, 3)
torch.add(x, y, out=result)
result

tensor([[-1.1850, -0.5089,  0.1015],
        [ 1.4024,  1.3383,  0.3002],
        [-1.0638, -0.1056,  1.5596],
        [ 1.2453, -0.2089,  0.8919],
        [ 1.0016, -0.7264,  0.5490]])

In [29]:
x[0,0].item()

-1.7858059406280518

In [31]:
x.numpy()

array([[-1.785806  , -0.8826238 , -0.7851814 ],
       [ 1.0577219 ,  0.7124949 , -0.31108364],
       [-1.4346391 , -0.39353952,  0.8644093 ],
       [ 0.36277336, -0.22206235,  0.6359759 ],
       [ 0.37936154, -1.6382465 , -0.10912111]], dtype=float32)

In [32]:
if torch.cuda.is_available():
    devices = torch.device('cuda')
    y = torch.ones_like(x, device=devices)

In [35]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [36]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [42]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
y

tensor([ 0.8002, -0.1446, -0.4348], requires_grad=True)


tensor([1638.8936, -296.0715, -890.4516], grad_fn=<MulBackward0>)

In [45]:
nn.Conv2d?

In [37]:
torch.randn?